server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      force: true

spring:
  application:
    name: UrlLify
  data:
    mongodb:
      uri: mongodb://localhost:27017/urlLify
    redis:
      host: localhost
      port: 6379
      database: 0

logging:
  pattern:
    console: "[%d{HH:mm:ss.SS}][%-5level][%logger.%method:line%line] - %msg%n"
  level:
    org:
      hibernate:
        type.descriptor.sql: trace
        SQL: debug
